default_stages: [pre-commit]
exclude: ^alembic/|^.local/|^.deploy/|^.venv/|^logs/|^reports/
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
        - id: check-ast
        - id: check-builtin-literals
        - id: debug-statements
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: requirements-txt-fixer
        - id: check-case-conflict
        - id: check-docstring-first
        - id: check-added-large-files
        - id: mixed-line-ending
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
    -   id: ruff-format
        files: ^(api|tests)/.*$
    - id: ruff
      args: [ --fix ]
      files: ^(api|tests)/.*$
