[tool.ruff]
line-length = 99

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
select = ["E", "F", "B", "Q", "W", "N"]
ignore = ["B007", "N999", "N811"]

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"
